config/routes.rb
Rails.application.routes.draw do
  resources :mii2s
  resources :miis
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mii.rb
class Mii < ApplicationRecord
end

app/models/mii2.rb
class Mii2 < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mii2s_controller.rb
class Mii2sController < ApplicationController
  before_action :set_mii2, only: %i[ show edit update destroy ]

  # GET /mii2s or /mii2s.json
  def index
    @mii2s = Mii2.all
  end

  # GET /mii2s/1 or /mii2s/1.json
  def show
  end

  # GET /mii2s/new
  def new
    @mii2 = Mii2.new
  end

  # GET /mii2s/1/edit
  def edit
  end

  # POST /mii2s or /mii2s.json
  def create
    @mii2 = Mii2.new(mii2_params)

    respond_to do |format|
      if @mii2.save
        format.html { redirect_to mii2_url(@mii2), notice: "Mii2 was successfully created." }
        format.json { render :show, status: :created, location: @mii2 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mii2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mii2s/1 or /mii2s/1.json
  def update
    respond_to do |format|
      if @mii2.update(mii2_params)
        format.html { redirect_to mii2_url(@mii2), notice: "Mii2 was successfully updated." }
        format.json { render :show, status: :ok, location: @mii2 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mii2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mii2s/1 or /mii2s/1.json
  def destroy
    @mii2.destroy!

    respond_to do |format|
      format.html { redirect_to mii2s_url, notice: "Mii2 was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mii2
      @mii2 = Mii2.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mii2_params
      params.require(:mii2).permit(:name, :lastname, :nickname, :slogan, :image, :age, :keyword, :description)
    end
end

app/controllers/miis_controller.rb
class MiisController < ApplicationController
  before_action :set_mii, only: %i[ show edit update destroy ]

  # GET /miis or /miis.json
  def index
    @miis = Mii.all
  end

  # GET /miis/1 or /miis/1.json
  def show
  end

  # GET /miis/new
  def new
    @mii = Mii.new
  end

  # GET /miis/1/edit
  def edit
  end

  # POST /miis or /miis.json
  def create
    @mii = Mii.new(mii_params)

    respond_to do |format|
      if @mii.save
        format.html { redirect_to mii_url(@mii), notice: "Mii was successfully created." }
        format.json { render :show, status: :created, location: @mii }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mii.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miis/1 or /miis/1.json
  def update
    respond_to do |format|
      if @mii.update(mii_params)
        format.html { redirect_to mii_url(@mii), notice: "Mii was successfully updated." }
        format.json { render :show, status: :ok, location: @mii }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mii.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miis/1 or /miis/1.json
  def destroy
    @mii.destroy!

    respond_to do |format|
      format.html { redirect_to miis_url, notice: "Mii was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mii
      @mii = Mii.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mii_params
      params.require(:mii).permit(:name, :lastname, :nickname, :slogan, :image, :age, :keyword, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mii2s_helper.rb
module Mii2sHelper
end

app/helpers/miis_helper.rb
module MiisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mmii</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mii2s/_form.html.erb
<%= form_with(model: mii2) do |form| %>
  <% if mii2.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mii2.errors.count, "error") %> prohibited this mii2 from being saved:</h2>

      <ul>
        <% mii2.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :slogan, style: "display: block" %>
    <%= form.text_area :slogan %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_area :image %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :keyword, style: "display: block" %>
    <%= form.text_field :keyword %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mii2s/_mii2.html.erb
<div id="<%= dom_id mii2 %>">
  <p>
    <strong>Name:</strong>
    <%= mii2.name %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= mii2.lastname %>
  </p>

  <p>
    <strong>Nickname:</strong>
    <%= mii2.nickname %>
  </p>

  <p>
    <strong>Slogan:</strong>
    <%= mii2.slogan %>
  </p>

  <p>
    <strong>Image:</strong>
  </p>
  <%= image_tag mii2.image %>
  <p>
    <strong>Age:</strong>
    <%= mii2.age %>
  </p>

  <p>
    <strong>Keyword:</strong>
    <%= mii2.keyword %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= mii2.description %>
  </p>

</div>

app/views/mii2s/edit.html.erb
<h1>Editing mii2</h1>

<%= render "form", mii2: @mii2 %>

<br>

<div>
  <%= link_to "Show this mii2", @mii2 %> |
  <%= link_to "Back to mii2s", mii2s_path %>
</div>

app/views/mii2s/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mii2s</h1>

<div id="mii2s">
  <% @mii2s.each do |mii2| %>
    <%= render mii2 %>
    <p>
      <%= link_to "Show this mii2", mii2 %>
    </p>
  <% end %>
</div>

<%= link_to "New mii2", new_mii2_path %>

app/views/mii2s/new.html.erb
<h1>New mii2</h1>

<%= render "form", mii2: @mii2 %>

<br>

<div>
  <%= link_to "Back to mii2s", mii2s_path %>
</div>

app/views/mii2s/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mii2 %>

<div>
  <%= link_to "Edit this mii2", edit_mii2_path(@mii2) %> |
  <%= link_to "Back to mii2s", mii2s_path %>

  <%= button_to "Destroy this mii2", @mii2, method: :delete %>
</div>

app/views/miis/_form.html.erb
<%= form_with(model: mii) do |form| %>
  <% if mii.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mii.errors.count, "error") %> prohibited this mii from being saved:</h2>

      <ul>
        <% mii.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :slogan, style: "display: block" %>
    <%= form.text_area :slogan %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_area :image %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :keyword, style: "display: block" %>
    <%= form.text_field :keyword %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/miis/_mii.html.erb
<div id="<%= dom_id mii %>">
  <p>
    <strong>Name:</strong>
    <%= mii.name %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= mii.lastname %>
  </p>

  <p>
    <strong>Nickname:</strong>
    <%= mii.nickname %>
  </p>

  <p>
    <strong>Slogan:</strong>
    <%= mii.slogan %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= mii.image %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= mii.age %>
  </p>

  <p>
    <strong>Keyword:</strong>
    <%= mii.keyword %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= mii.description %>
  </p>

</div>

app/views/miis/edit.html.erb
<h1>Editing mii</h1>

<%= render "form", mii: @mii %>

<br>

<div>
  <%= link_to "Show this mii", @mii %> |
  <%= link_to "Back to miis", miis_path %>
</div>

app/views/miis/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Miis</h1>

<div id="miis">
  <% @miis.each do |mii| %>
    <%= render mii %>
    <p>
      <%= link_to "Show this mii", mii %>
    </p>
  <% end %>
</div>

<%= link_to "New mii", new_mii_path %>

app/views/miis/new.html.erb
<h1>New mii</h1>

<%= render "form", mii: @mii %>

<br>

<div>
  <%= link_to "Back to miis", miis_path %>
</div>

app/views/miis/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mii %>

<div>
  <%= link_to "Edit this mii", edit_mii_path(@mii) %> |
  <%= link_to "Back to miis", miis_path %>

  <%= button_to "Destroy this mii", @mii, method: :delete %>
</div>